# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder ".", "/vagrant", type: "nfs"

  config.vm.define "test" do |test|
    test.vm.box = "jonludlam/xs-ubuntu-trusty"
    test.vm.provision "shell", path: "install_xen.sh"
  end

  config.vm.define "dev" do |dev|
    dev.vm.box = "jonludlam/xs-ubuntu-trusty"
    dev.vm.provision "shell", path: "dev_provision.sh"
  end

  config.vm.provider :xenserver do |xs|
    xs.memory = 4096
  end
end
