# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

$script = <<SCRIPT
echo I am provisioning...
date > /etc/vagrant_provisioned_at
SCRIPT

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|
  config.vm.synced_folder ".", "/vagrant", type: "nfs"
  config.vm.synced_folder "../repos", "/repos", type:"nfs", mount_options: ['rw', 'vers=4', 'tcp', 'fsc', 'rsize=8192', 'wsize=8192', 'noatime']

  config.vm.provider :xenserver do |xs|
    xs.memory = 4096
  end

  config.vm.define "dev" do |dev|
    dev.vm.box = "jonludlam/xs-centos-7"
    dev.vm.provision "shell", path: "dev_provision.sh"
    dev.vm.provision "file", source: "~/.gitconfig", destination: "~/.gitconfig"
    dev.vm.provision "shell", inline: "hostname vg-tr3-dev; echo vg-tr3-dev > /etc/hostname"
    dev.vm.provider :xenserver do |xs|
	xs.pv = true
    end
  end

  config.vm.define "test" do |test|
    test.vm.box_check_update = true
    test.vm.box = "jonludlam/xs-trunk-ring3"
    test.vm.provision "shell", inline: "hostname vg-tr3-test; echo vg-tr3-test > /etc/hostname"
#    test.vm.provision "shell", path: "test_provision.sh"
  end
end
